import test from"node:test";import assert from"node:assert/strict";import{mkdtempSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{createServer}from"node:http";import{DEFAULT_CONFIG,ExternalSigner,RouterLogger,RouterRepository,SessionRouter,StaticCandidateProvider,preflight,preflightMany,redact,type MinerCandidate}from"../src/index.js";import{createRouterServer}from"../src/server.js";
const candidate:MinerCandidate={id:"m",identity:{},enabled:true,capabilities:[{modelId:"model",assurance:"SOFT"}],price:{amount:"11",asset:"FLOP",unit:"turn"}};
function repo(){const dir=mkdtempSync(join(tmpdir(),"router-sec-")),r=new RouterRepository(join(dir,"r.db"));return{dir,r,close(){r.close();rmSync(dir,{recursive:true,force:true});}};}
test("price is a hard gate and FailedAck penalty is deterministic",async()=>{const x=repo();try{const router=new SessionRouter(new StaticCandidateProvider([candidate]),x.r);let d=await router.route({requestId:"p",constraints:{modelId:"model",maximumPrice:{amount:"10",asset:"FLOP",unit:"turn"}}});assert.equal(d.status,"NO_ELIGIBLE_MINER");router.recordFailedAck({id:"f1",minerId:"m",source:"fixture",observedAt:new Date().toISOString()});d=await router.route({requestId:"f",constraints:{modelId:"model"}});assert.ok(d.snapshot.evaluations[0]!.score!.failedAckPenalty<0);}finally{x.close();}});
test("preflight deadline aborts hostile endpoint",async()=>{const server=createServer((_q,_r)=>{});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const address=server.address();assert.ok(address&&typeof address!=="string");try{const result=await preflight({...candidate,endpoint:{url:`http://127.0.0.1:${address.port}`,protocol:"http"}},{...DEFAULT_CONFIG,allowPrivateEndpoints:true,preflightTimeoutMs:25});assert.equal(result.status,"FAIL");}finally{server.closeAllConnections();server.close();}});
test("API health, provider-scoped miners and payload limit",async()=>{const x=repo(),router=new SessionRouter(new StaticCandidateProvider([candidate]),x.r),server=createRouterServer(router,x.r);await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const a=server.address();assert.ok(a&&typeof a!=="string");try{const base=`http://127.0.0.1:${a.port}`;assert.equal((await fetch(`${base}/healthz`)).status,200);const miners=await(await fetch(`${base}/v1/miners`)).json()as any;assert.equal(miners.status,"provider_scoped");assert.equal(miners.miners[0].id,"m");assert.equal((await fetch(`${base}/v1/miners/m`)).status,200);assert.equal((await fetch(`${base}/v1/miners/missing`)).status,404);const oversized="x".repeat(70_000);assert.equal((await fetch(`${base}/v1/route`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({oversized})})).status,413);}finally{server.close();x.close();}});
test("structured logs redact secrets",()=>{const events:Record<string,unknown>[]=[];new RouterLogger(events.push.bind(events)).event("test",{authorization:"Bearer x",nested:{privateKey:"x"}});const text=JSON.stringify(events);assert.ok(!text.includes("Bearer x"));assert.ok(!text.includes('privateKey":"x'));assert.equal((redact({password:"x"})as any).password,"[REDACTED]");});
test("preflight concurrency is bounded and result order deterministic",async()=>{const values=Array.from({length:5},(_,i)=>({...candidate,id:`m${i}`,endpoint:{url:"http://127.0.0.1",protocol:"http"}}));let active=0,peak=0;const fetcher=async()=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,5));active--;return new Response(null,{status:200});};const results=await preflightMany(values,{...DEFAULT_CONFIG,allowPrivateEndpoints:true,preflightConcurrency:2},fetcher as typeof fetch);assert.ok(peak<=2);assert.deepEqual(results.map(x=>x.minerId),values.map(x=>x.id));});
test("ExternalSigner times out and rejects non-strict responses",async()=>{let mode="invalid";const server=createServer((_req,res)=>{if(mode==="timeout")return;res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({type:"test",publicKey:"key",extra:true}));});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const a=server.address();assert.ok(a&&typeof a!=="string");try{const signer=new ExternalSigner(`http://127.0.0.1:${a.port}`,undefined,{allowPrivateEndpoint:true,timeoutMs:20,maxResponseBytes:1024});await assert.rejects(()=>signer.getIdentity(),/INVALID_RESPONSE/);mode="timeout";await assert.rejects(()=>signer.getIdentity(),/TIMEOUT/);}finally{server.closeAllConnections();server.close();}});
