import { randomUUID } from "node:crypto";
import { sha256,round } from "./canonical.js";
import { preflightMany } from "./preflight.js";
import type { CandidateEvaluation, MinerCandidate, PreflightResult, RouteDecision, RouteRequest, RouterConfig, ScoreBreakdown, SessionAttempt, SessionOutcome } from "./types.js";
import { DEFAULT_CONFIG } from "./types.js";
import type { MinerCandidateProvider } from "./providers.js";
import { RouterRepository } from "./storage.js";
import { RouterLogger } from "./observability.js";
export const ROUTER_VERSION="0.1.0";
const assurance={UNKNOWN:0,SOFT:1,HARD:2};
const norm=(n:number|undefined,fallback=0)=>n===undefined?fallback:Math.max(0,Math.min(1,n));
export interface SessionExecutor { execute(candidate:MinerCandidate,request:RouteRequest,signal:AbortSignal):Promise<{status:"completed"|"failed";retryable?:boolean;reason?:string}>; }
export class SessionRouter {
 constructor(private provider:MinerCandidateProvider,private repo:RouterRepository,private config:RouterConfig=DEFAULT_CONFIG,private clock:()=>Date=()=>new Date(),private logger=new RouterLogger()){}
 private reject(c:MinerCandidate,r:RouteRequest,p:PreflightResult):string[]{const x=r.constraints,cap=c.capabilities.find(v=>v.modelId===x.modelId);const out:string[]=[];if(!c.enabled)out.push("DISABLED");if(!cap)return [...out,"MODEL_MISMATCH"];if(x.modelHash&&cap.modelHash!==x.modelHash)out.push(cap.modelHash?"MODEL_HASH_MISMATCH":"INSUFFICIENT_CAPABILITY_DATA");if(x.precision&&!cap.precisions?.includes(x.precision))out.push("PRECISION_UNSUPPORTED");if(x.decodePolicy&&!cap.decodePolicies?.includes(x.decodePolicy))out.push("DECODE_POLICY_UNSUPPORTED");if(x.minimumAssurance&&assurance[cap.assurance]<assurance[x.minimumAssurance])out.push("ASSURANCE_TOO_LOW");if(x.capabilityMaxAgeMs&&(!cap.observedAt||this.clock().getTime()-Date.parse(cap.observedAt)>x.capabilityMaxAgeMs))out.push("CAPABILITY_STALE");if(x.maxLatencyMs!==undefined){const observed=p.status==="PASS"?p.latencyMs:c.telemetry?.latencyMsEwma;if(observed===undefined)out.push("INSUFFICIENT_CAPABILITY_DATA");else if(observed>x.maxLatencyMs)out.push("LATENCY_EXCEEDS_MAXIMUM");}if(x.maximumPrice){if(!c.price||c.price.asset!==x.maximumPrice.asset||c.price.unit!==x.maximumPrice.unit)out.push("INSUFFICIENT_CAPABILITY_DATA");else if(!/^\d+$/.test(c.price.amount)||!/^\d+$/.test(x.maximumPrice.amount)||BigInt(c.price.amount)>BigInt(x.maximumPrice.amount))out.push("PRICE_EXCEEDS_MAXIMUM");}const circuit=this.repo.circuit(c.id);if(circuit.state==="OPEN"&&circuit.openedAt){if(this.clock().getTime()-Date.parse(circuit.openedAt)<this.config.circuitCooldownMs)out.push("COOLDOWN_ACTIVE");else this.repo.setCircuit(c.id,circuit.failures,"HALF_OPEN",circuit.openedAt);}if(r.preflight&&p.status!=="PASS")out.push("PREFLIGHT_FAILED");return [...new Set(out)];}
 private score(c:MinerCandidate,p:PreflightResult,request:RouteRequest):ScoreBreakdown{const now=this.clock().getTime(),cap=c.capabilities.find(v=>v.modelId===request.constraints.modelId),t=c.telemetry??{},w=this.config.weights;const success=round(norm(t.successEwma,.5)*w.success),latency=round((1-norm((t.latencyMsEwma??this.config.preflightTimeoutMs)/this.config.preflightTimeoutMs))*w.latency),freshness=round((cap?.observedAt?Math.exp(-(now-Date.parse(cap.observedAt))/86_400_000):0)*w.freshness),pf=round((p.status==="PASS"?1:p.status==="SKIPPED"?.5:0)*w.preflight),a=round((cap?assurance[cap.assurance]/2:0)*w.assurance),availability=round(norm(t.availability,.5)*w.availability);const failed=this.repo.failedAcks(c.id).reduce((s,o)=>s+Math.exp(-(now-Date.parse(o.observedAt))*Math.LN2/this.config.failedAckHalfLifeMs),0);const failedAckPenalty=round(-Math.min(w.failedAckPenalty,failed*w.failedAckPenalty));const circuitPenalty=this.repo.circuit(c.id).state==="HALF_OPEN"?round(-.25*w.circuitPenalty):0;const total=round(success+latency+freshness+pf+a+availability+failedAckPenalty+circuitPenalty);return {success,latency,freshness,preflight:pf,assurance:a,availability,failedAckPenalty,circuitPenalty,total};}
async route(request:RouteRequest):Promise<RouteDecision>{if(!request.requestId||!request.constraints?.modelId)throw new Error("INVALID_ROUTE_REQUEST");let candidates:MinerCandidate[];try{candidates=await this.provider.candidates(request);}catch(e){if(e instanceof Error&&e.message==="RUNTIME_UNAVAILABLE")return this.persist(request,[],[],"RUNTIME_UNAVAILABLE");throw e;}candidates.sort((a,b)=>a.id.localeCompare(b.id));const preflights=request.preflight?await preflightMany(candidates,this.config):candidates.map(c=>({minerId:c.id,status:"SKIPPED",checkedAt:this.clock().toISOString()}as PreflightResult));const evaluations=candidates.map((c,index)=>{const p=preflights[index]!;const reasons=this.reject(c,request,p);return{minerId:c.id,eligible:reasons.length===0,rejectionReasons:reasons,score:reasons.length?undefined:this.score(c,p,request),preflight:p};});const ranking=evaluations.filter(x=>x.eligible).sort((a,b)=>(b.score!.total-a.score!.total)||a.minerId.localeCompare(b.minerId)).map(x=>x.minerId);return this.persist(request,candidates,evaluations,ranking.length?"SELECTED":"NO_ELIGIBLE_MINER",ranking);}
private persist(request:RouteRequest,candidates:MinerCandidate[],evaluations:CandidateEvaluation[],status:RouteDecision["status"],ranking:string[]=[]):RouteDecision{const capturedAt=this.clock().toISOString();const snapshot={request,candidates,evaluations,config:this.config,routerVersion:ROUTER_VERSION,capturedAt};const d:RouteDecision={decisionId:`decision_${randomUUID()}`,selectedMinerId:ranking[0],status,ranking,snapshot,configHash:sha256(this.config),snapshotHash:sha256(snapshot)};this.repo.saveDecision(d);for(const e of evaluations)this.repo.savePreflight(d.decisionId,e.preflight);this.logger.event("route.decision",{decisionId:d.decisionId,requestId:request.requestId,status,candidateCount:candidates.length,eligibleCount:ranking.length,selectedMinerId:d.selectedMinerId});return d;}
 recordFailedAck(observation:import("./types.js").FailedAckObservation){if(!observation.id||!observation.minerId||!Number.isFinite(Date.parse(observation.observedAt)))throw new Error("INVALID_FAILED_ACK");this.repo.saveFailedAck(observation);this.logger.event("failed_ack.observed",{id:observation.id,minerId:observation.minerId,source:observation.source});}
 replay(id:string):{status:"REPLAY_MATCH"|"DECISION_REPLAY_DIVERGENCE";original:RouteDecision;recomputedRanking:string[]}{const d=this.repo.decision(id);if(!d)throw new Error("DECISION_NOT_FOUND");const ranking=d.snapshot.evaluations.filter(x=>x.eligible).sort((a,b)=>(b.score!.total-a.score!.total)||a.minerId.localeCompare(b.minerId)).map(x=>x.minerId);return {status:JSON.stringify(ranking)===JSON.stringify(d.ranking)&&sha256(d.snapshot.config)===d.configHash?"REPLAY_MATCH":"DECISION_REPLAY_DIVERGENCE",original:d,recomputedRanking:ranking};}
 async execute(decision:RouteDecision,executor:SessionExecutor):Promise<SessionOutcome>{const attempts:SessionAttempt[]=[];const max=Math.min(decision.snapshot.request.maxAttempts??3,decision.ranking.length);for(let i=0;i<max;i++){const miner=decision.snapshot.candidates.find(x=>x.id===decision.ranking[i])!;const attempt:SessionAttempt={id:`attempt_${randomUUID()}`,decisionId:decision.decisionId,minerId:miner.id,attempt:i+1,startedAt:this.clock().toISOString(),outcome:"attempted"};const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),this.config.preflightTimeoutMs);try{const result=await executor.execute(miner,decision.snapshot.request,ctl.signal);attempt.completedAt=this.clock().toISOString();attempt.outcome=result.status;attempt.retryable=result.retryable;attempt.reason=result.reason;this.recordCircuit(miner.id,result.status==="completed");}catch(e){attempt.completedAt=this.clock().toISOString();attempt.outcome=ctl.signal.aborted?"timed_out":"failed";attempt.retryable=true;attempt.reason=e instanceof Error?e.message:"FAILED";this.recordCircuit(miner.id,false);}finally{clearTimeout(timer);this.repo.saveAttempt(attempt);attempts.push(attempt);}if(attempt.outcome==="completed"){const out={decisionId:decision.decisionId,status:"completed",attempts,selectedMinerId:miner.id}as SessionOutcome;this.repo.saveOutcome(out);return out;}if(!attempt.retryable)break;}const out={decisionId:decision.decisionId,status:attempts.at(-1)?.outcome??"failed",attempts}as SessionOutcome;this.repo.saveOutcome(out);return out;}
 async miners():Promise<{status:"provider_scoped";provider:string;miners:MinerCandidate[]}>{return{status:"provider_scoped",provider:this.provider.name,miners:this.provider.snapshot?await this.provider.snapshot():[]};}
 private recordCircuit(id:string,ok:boolean){const c=this.repo.circuit(id);if(ok)return this.repo.setCircuit(id,0,"CLOSED");const failures=c.failures+1;this.repo.setCircuit(id,failures,failures>=this.config.circuitFailureThreshold?"OPEN":"CLOSED",failures>=this.config.circuitFailureThreshold?this.clock().toISOString():undefined);}
}
