import { generateKeyPairSync, sign as cryptoSign, createPrivateKey } from "node:crypto";
import { canonical, sha256 } from "./canonical.js";
import { validateEndpoint } from "./preflight.js";

export type SigningDomain="FLOP_ROUTER_SESSION_V1"|"FLOP_ROUTER_DECISION_V1";
export interface ValidatedSignRequest { domain:SigningDomain; kind:"session"|"decision"; payload:Record<string,unknown>; canonicalPayload:string; }
export interface SignerIdentity { type:string; publicKey:string; }
export interface SignResult { identity:SignerIdentity; signature:string; payloadHash:string; }
export interface Signer { getIdentity():Promise<SignerIdentity>; sign(request:ValidatedSignRequest):Promise<SignResult>; }
export interface ExternalSignerOptions { timeoutMs?:number; maxResponseBytes?:number; allowPrivateEndpoint?:boolean; }
export function validateSignRequest(domain:SigningDomain,kind:"session"|"decision",payload:Record<string,unknown>):ValidatedSignRequest { const encoded=canonical(payload); if(canonical(JSON.parse(encoded))!==encoded) throw new Error("NON_CANONICAL_SIGN_REQUEST"); if(!["FLOP_ROUTER_SESSION_V1","FLOP_ROUTER_DECISION_V1"].includes(domain)) throw new Error("INVALID_SIGNING_DOMAIN"); return {domain,kind,payload,canonicalPayload:encoded}; }
export class EphemeralSigner implements Signer { private pair=generateKeyPairSync("ed25519"); async getIdentity(){return {type:"EPHEMERAL_TEST_ONLY",publicKey:this.pair.publicKey.export({format:"der",type:"spki"}).toString("base64")};} async sign(r:ValidatedSignRequest){ const identity=await this.getIdentity(); const bytes=Buffer.from(`${r.domain}|${r.kind}|${r.canonicalPayload}`); return {identity,signature:cryptoSign(null,bytes,this.pair.privateKey).toString("base64url"),payloadHash:sha256(r.payload)}; } }
const exact=(value:unknown,keys:string[])=>!!value&&!Array.isArray(value)&&typeof value==="object"&&Object.keys(value).sort().join("|")===keys.sort().join("|");
const identitySchema=(value:unknown):value is SignerIdentity=>exact(value,["type","publicKey"])&&typeof(value as SignerIdentity).type==="string"&&typeof(value as SignerIdentity).publicKey==="string"&&!!(value as SignerIdentity).publicKey;
const signSchema=(value:unknown):value is SignResult=>exact(value,["identity","signature","payloadHash"])&&identitySchema((value as SignResult).identity)&&typeof(value as SignResult).signature==="string"&&!!(value as SignResult).signature&&/^sha256:[0-9a-f]{64}$/.test((value as SignResult).payloadHash);
async function boundedJson(response:Response,maxBytes:number):Promise<unknown>{const declared=Number(response.headers.get("content-length")??0);if(declared>maxBytes)throw new Error("EXTERNAL_SIGNER_RESPONSE_TOO_LARGE");if(!response.body)throw new Error("EXTERNAL_SIGNER_INVALID_RESPONSE");const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;if(value){size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new Error("EXTERNAL_SIGNER_RESPONSE_TOO_LARGE");}chunks.push(value);}}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new Error("EXTERNAL_SIGNER_INVALID_RESPONSE");}}
export class ExternalSigner implements Signer {
 private options:Required<ExternalSignerOptions>;
 constructor(private endpoint:string,private token?:string,options:ExternalSignerOptions={}){this.options={timeoutMs:options.timeoutMs??2_000,maxResponseBytes:options.maxResponseBytes??32*1024,allowPrivateEndpoint:options.allowPrivateEndpoint??false};}
 private async call(path:string,body?:unknown){const base=await validateEndpoint(this.endpoint,this.options.allowPrivateEndpoint),url=new URL(path,base);if(url.origin!==base.origin)throw new Error("EXTERNAL_SIGNER_INVALID_ENDPOINT");const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),this.options.timeoutMs);try{const r=await fetch(url,{method:body?"POST":"GET",headers:{accept:"application/json","content-type":"application/json",...(this.token?{authorization:`Bearer ${this.token}`}:{})},body:body?JSON.stringify(body):undefined,signal:ctl.signal,redirect:"error"});if(!r.ok)throw new Error("EXTERNAL_SIGNER_UNAVAILABLE");return await boundedJson(r,this.options.maxResponseBytes);}catch(e){if(ctl.signal.aborted)throw new Error("EXTERNAL_SIGNER_TIMEOUT");throw e;}finally{clearTimeout(timer);}}
 async getIdentity(){const value=await this.call("/v1/identity");if(!identitySchema(value))throw new Error("EXTERNAL_SIGNER_INVALID_RESPONSE");return value;}
 async sign(r:ValidatedSignRequest){const value=await this.call("/v1/sign",r);if(!signSchema(value)||value.payloadHash!==sha256(r.payload))throw new Error("EXTERNAL_SIGNER_INVALID_RESPONSE");return value;}
}
export class SecretInjectedSigner implements Signer { private key; constructor(derBase64:string|undefined,explicitOptIn=false){if(!explicitOptIn||!derBase64)throw new Error("SIGNER_UNAVAILABLE");this.key=createPrivateKey({key:Buffer.from(derBase64,"base64"),format:"der",type:"pkcs8"});} async getIdentity(){return {type:"SECRET_INJECTED",publicKey:"REDACTED_BY_DESIGN"};} async sign(r:ValidatedSignRequest){return {identity:await this.getIdentity(),signature:cryptoSign(null,Buffer.from(`${r.domain}|${r.kind}|${r.canonicalPayload}`),this.key).toString("base64url"),payloadHash:sha256(r.payload)};} }
