import { generateKeyPairSync, sign as cryptoSign, createPrivateKey } from "node:crypto";
import { canonical, sha256 } from "./canonical.js";

export type SigningDomain="FLOP_ROUTER_SESSION_V1"|"FLOP_ROUTER_DECISION_V1";
export interface ValidatedSignRequest { domain:SigningDomain; kind:"session"|"decision"; payload:Record<string,unknown>; canonicalPayload:string; }
export interface SignerIdentity { type:string; publicKey:string; }
export interface SignResult { identity:SignerIdentity; signature:string; payloadHash:string; }
export interface Signer { getIdentity():Promise<SignerIdentity>; sign(request:ValidatedSignRequest):Promise<SignResult>; }
export function validateSignRequest(domain:SigningDomain,kind:"session"|"decision",payload:Record<string,unknown>):ValidatedSignRequest { const encoded=canonical(payload); if(canonical(JSON.parse(encoded))!==encoded) throw new Error("NON_CANONICAL_SIGN_REQUEST"); if(!["FLOP_ROUTER_SESSION_V1","FLOP_ROUTER_DECISION_V1"].includes(domain)) throw new Error("INVALID_SIGNING_DOMAIN"); return {domain,kind,payload,canonicalPayload:encoded}; }
export class EphemeralSigner implements Signer { private pair=generateKeyPairSync("ed25519"); async getIdentity(){return {type:"EPHEMERAL_TEST_ONLY",publicKey:this.pair.publicKey.export({format:"der",type:"spki"}).toString("base64")};} async sign(r:ValidatedSignRequest){ const identity=await this.getIdentity(); const bytes=Buffer.from(`${r.domain}|${r.kind}|${r.canonicalPayload}`); return {identity,signature:cryptoSign(null,bytes,this.pair.privateKey).toString("base64url"),payloadHash:sha256(r.payload)}; } }
export class ExternalSigner implements Signer { constructor(private endpoint:string,private token?:string){} private async call(path:string,body?:unknown){const r=await fetch(new URL(path,this.endpoint),{method:body?"POST":"GET",headers:{"content-type":"application/json",...(this.token?{authorization:`Bearer ${this.token}`}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error("EXTERNAL_SIGNER_UNAVAILABLE");return r.json();} async getIdentity(){return this.call("/v1/identity") as Promise<SignerIdentity>;} async sign(r:ValidatedSignRequest){return this.call("/v1/sign",r) as Promise<SignResult>;} }
export class SecretInjectedSigner implements Signer { private key; constructor(derBase64:string|undefined,explicitOptIn=false){if(!explicitOptIn||!derBase64)throw new Error("SIGNER_UNAVAILABLE");this.key=createPrivateKey({key:Buffer.from(derBase64,"base64"),format:"der",type:"pkcs8"});} async getIdentity(){return {type:"SECRET_INJECTED",publicKey:"REDACTED_BY_DESIGN"};} async sign(r:ValidatedSignRequest){return {identity:await this.getIdentity(),signature:cryptoSign(null,Buffer.from(`${r.domain}|${r.kind}|${r.canonicalPayload}`),this.key).toString("base64url"),payloadHash:sha256(r.payload)};} }
